In [78]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/feature_engineered_gpu_dataset.csv")

df.head()

,manufacturer,gpu_name,releaseyear,memsize,gpuclock,memclock,unifiedshader,tmu,rop,igp,...,tdp,powerperformance,testdate,category,opencl,performance_per_watt,performance_per_gb,performance_per_shader,gpu_age,performance_category
0,AMD,RADEON RX 6500 XT,2022.0,4.0,1560,1313.0,10752.0,336,112,No,...,NaN,NaN,2022,Unknown,52512.0,NaN,2361.250,0.878441,4.0,Extreme
1,AMD,RADEON RX 6400,2022.0,4.0,1395,1219.0,10496.0,328,112,No,...,NaN,NaN,2022,Unknown,NaN,NaN,1739.500,0.662919,4.0,Extreme
2,AMD,RADEON PRO W6400,2022.0,4.0,1080,2000.0,10240.0,320,96,No,...,NaN,NaN,2022,Unknown,NaN,NaN,1479.000,0.577734,4.0,Extreme
3,NVIDIA,GEFORCE RTX 3090 TI,2022.0,24.0,1980,1313.0,7168.0,224,80,No,...,450.0,64.65,2022,Unknown,229738.0,64.653333,1212.250,4.058873,4.0,Extreme
4,AMD,RADEON RX 6700S,2022.0,8.0,1440,945.0,4096.0,256,64,No,...,NaN,NaN,2022,Unknown,72317.0,NaN,1498.625,2.927002,4.0,Extreme

In [79]:
df.dtypes

manufacturer                  str
gpu_name                      str
releaseyear               float64
memsize                   float64
gpuclock                    int64
memclock                  float64
unifiedshader             float64
tmu                         int64
rop                         int64
igp                           str
bus                           str
memtype                       str
gpuchip                       str
g3dmark                     int64
g2dmark                     int64
price                     float64
gpuvalue                  float64
tdp                       float64
powerperformance          float64
testdate                    int64
category                      str
opencl                    float64
performance_per_watt      float64
performance_per_gb        float64
performance_per_shader    float64
gpu_age                   float64
performance_category          str
dtype: object

In [80]:
selected_columns = [
    'manufacturer',
    'releaseyear',
    'memsize',
    'gpuclock',
    'memclock',
    'unifiedshader',
    'tmu',
    'rop',
    'g3dmark',
    'g2dmark',
    'price',
    'gpuvalue',
    'tdp',
    'powerperformance',
    'opencl',
    'performance_per_watt',
    'performance_per_gb',
    'performance_per_shader',
    'gpu_age',
    'performance_category'
]

df = df[selected_columns]

In [81]:
from sklearn.preprocessing import LabelEncoder

manufacturer_encoder = LabelEncoder()

df["manufacturer"] = manufacturer_encoder.fit_transform(
    df["manufacturer"]
)

df.head()

,manufacturer,releaseyear,memsize,gpuclock,memclock,unifiedshader,tmu,rop,g3dmark,g2dmark,price,gpuvalue,tdp,powerperformance,opencl,performance_per_watt,performance_per_gb,performance_per_shader,gpu_age,performance_category
0,0,2022.0,4.0,1560,1313.0,10752.0,336,112,9445,910,199.99,47.23,NaN,NaN,52512.0,NaN,2361.250,0.878441,4.0,Extreme
1,0,2022.0,4.0,1395,1219.0,10496.0,328,112,6958,899,159.99,43.49,NaN,NaN,NaN,NaN,1739.500,0.662919,4.0,Extreme
2,0,2022.0,4.0,1080,2000.0,10240.0,320,96,5916,621,NaN,NaN,NaN,NaN,NaN,NaN,1479.000,0.577734,4.0,Extreme
3,2,2022.0,24.0,1980,1313.0,7168.0,224,80,29094,1117,2099.99,13.85,450.0,64.65,229738.0,64.653333,1212.250,4.058873,4.0,Extreme
4,0,2022.0,8.0,1440,945.0,4096.0,256,64,11989,829,NaN,NaN,NaN,NaN,72317.0,NaN,1498.625,2.927002,4.0,Extreme

In [90]:
X_reg = df.drop(
    columns=[
        "g3dmark",
        "performance_category"
    ]
)

y_reg = df["g3dmark"]

In [91]:
performance_encoder = LabelEncoder()

df["performance_category"] = performance_encoder.fit_transform(
    df["performance_category"]
)

X_clf = df.drop("performance_category", axis=1)

y_clf = df["performance_category"]

In [92]:
from sklearn.model_selection import train_test_split

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.20,
    random_state=42
)

In [93]:
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
    X_clf,
    y_clf,
    test_size=0.20,
    random_state=42,
    stratify=y_clf
)

In [94]:
from sklearn.preprocessing import StandardScaler

reg_scaler = StandardScaler()

X_train_reg_scaled = reg_scaler.fit_transform(
    X_train_reg
)

X_test_reg_scaled = reg_scaler.transform(
    X_test_reg
)

In [99]:
df.isnull().sum()

manufacturer                0
releaseyear                 0
memsize                     0
gpuclock                    0
memclock                    0
unifiedshader               0
tmu                         0
rop                         0
g3dmark                     0
g2dmark                     0
tdp                       569
powerperformance          569
performance_per_watt      569
performance_per_gb          0
performance_per_shader      0
gpu_age                     0
performance_category        0
dtype: int64

In [100]:
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent.sort_values(ascending=False)

powerperformance          48.841202
tdp                       48.841202
performance_per_watt      48.841202
manufacturer               0.000000
releaseyear                0.000000
unifiedshader              0.000000
memsize                    0.000000
gpuclock                   0.000000
memclock                   0.000000
g3dmark                    0.000000
rop                        0.000000
tmu                        0.000000
g2dmark                    0.000000
performance_per_gb         0.000000
performance_per_shader     0.000000
gpu_age                    0.000000
performance_category       0.000000
dtype: float64

In [102]:
print(X_train_reg.select_dtypes(include=['object']).columns)

Index([], dtype='str')

In [106]:
from sklearn.preprocessing import LabelEncoder

performance_encoder = LabelEncoder()

df["performance_category"] = performance_encoder.fit_transform(
    df["performance_category"]
)

X_clf = df.drop("performance_category", axis=1)

y_clf = df["performance_category"]

In [107]:
print(X_train_reg.select_dtypes(include=['object']).columns)

Index([], dtype='str')